version: "3.1"

services:
  gostack.postgres:
    image: postgres
    container_name: gostack.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gobarber
    ports:
      - 5432:5432
  gostack.mongo:
    image: mongo
    container_name: gostack.mongo
    ports:
      - 27017:27017

