name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.3
      with:
        node-version: 12.x
      
      # Dependencies Install
    - name: Install Dependencies
      run: yarn
      
      # Run Build    
    - name: Run Build
      run: yarn build
    
    # Copy code to DigitalOcean
    - name: Copy folder to DigitalOcean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: ".,!node_modules"
        target: "~/app/gs-backend-ts-node-gobarber-lesson"
    
    # Run "yarn" on Digital Ocean
    
    # Run typeorm migrations
      
    # Restart Server
